### ISSUE TITLE
Build failing on Ubuntu 18.04 / can't run bash file

### ISSUE THREAD

**Issue by remokon** [dylmeadows/EonTimer#26]
Hey dylmeadows!

First of all: I couldn't manage to make neither the bash script nor the .bat w/ wine or mono work, so I tried to build it myself. When trying to build from source using gradle it failed, here's my output:
```
╰─$ ./gradlew distZip                                                                             1 ↵
Downloading https://services.gradle.org/distributions/gradle-5.2.1-all.zip
..............................................................................................................................
Unzipping /home//<user>/.gradle/wrapper/dists/gradle-5.2.1-all/bviwmvmbexq6idcscbicws5me/gradle-5.2.1-all.zip to /home//<user>/.gradle/wrapper/dists/gradle-5.2.1-all/bviwmvmbexq6idcscbicws5me
Set executable permissions for: /home/<user>/.gradle/wrapper/dists/gradle-5.2.1-all/bviwmvmbexq6idcscbicws5me/gradle-5.2.1/bin/gradle

Welcome to Gradle 5.2.1!

Here are the highlights of this release:
 - Define sets of dependencies that work together with Java Platform plugin
 - New C++ plugins with dependency management built-in
 - New C++ project types for gradle init
 - Service injection into plugins and project extensions

For more details see https://docs.gradle.org/5.2.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

```
Sorry if I'm missing something obvious, I'm not a huge gradle / java expert at all.

Cheers.

**Comment by remokon** [comment]
An update on the bash script (that I added in the title just for reference in case somebody is looking for it): I was actually finally able to make it run! The problem was that in your script when looking for the java home — that in my case was `/usr/bin/java` right away — there was an extra `bin/java` which messed up the reference. 
So I just changed it to: 
```if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME"
    fi
```
which is probably not ideal, but worked out for me the way java was installed.

About the gradle build: it was probably due to the fact that I had openjdk installed instead, while in the meantime I installed Oracle's.

Thanks for your great work, keep it up!

**Comment by dylmeadows** [comment]
Sorry I'm just now getting to this! The start script comes bundled with the application plugin for gradle. There is a way to customize the start script though. However, I think the best solution, if you haven't done this already, is to add `export JAVA_HOME="[insert location of your java installation]"` to either `.bashrc` or `.bash_profile` at the root of your home directory. Either way, I'm glad you were able to get it running. Let me know if you have any more issues.
