### ISSUE TITLE
Java error when launching on Windows 10

### ISSUE THREAD

**Issue by libjet** [dylmeadows/EonTimer#29]
When I run EonTimer.bat in CMD I get 
`Error: Could not find or load main class io.github.dylmeadows.eontimer.AppLauncher`
Running on Windows 10 with Java 1.8.0_231

**Comment by libjet** [comment]
Update: I uninstalled AdoptOpen JDK 11 and 13, and now I can successfully launch EonTimer. I'm not sure what happened, but I believe that the issue is caused by some kind of Java version mismatch.

**Comment by emeria** [comment]
Do you know what version of Java you are using for this now?  I have "8", but not sure if I have a different version of 8.  I am using Oracle JDK/JRE
