### ISSUE TITLE
how to run eon timer?

### ISSUE THREAD

**Issue by doxenking** [dylmeadows/EonTimer#75]
**I know this has already been posted but I have a slightly different question. I downloaded JRE 8 and the latest version of eon timer, but whenever I try to run 'EonTimer.bat' it opens up for a millisecond and then closes. I'm not sure what I'm doing wrong here...

(I didn't see a FAQ that applied to my situation so any help would be appreciated)**

on an unrelated note, to anyone who wants to download JRE 8 without creating an account:
click on the download that you want from the page at this website: https://www.oracle.com/java/technologies/javase-jre8-downloads.html
-> when the 'I reviewed and accept the Oracle Technology Network License Agreement for Oracle Java SE' checkbox pops up, check it, and copy the link in the box bellow it that says 'Download jre-8u251-windows-x64.exe'
-> paste the link in notepad (or any text editor)
-> in the link, find where it says otn, and add -pub to the end of it. it should look like this: 'otn-pub' within the link
-> copy everyting after the '=' sign
->paste it into the address search bar on your browser
->presto

**Comment by dylmeadows** [comment]
Is there a .log file in the bin directory that you can upload? Should help me figure out why it's not working.

**Comment by Hotheed** [comment]
I'm having the exact same issue. I've installed JRE 8 and have tried running the EonTimer.bat file, only for it to open a command prompt for a second and close. Tried downloading again, reinstalling JRE 8 too, though it doesn't seem to be working. I'm not getting any .log file so I'm not able to upload anything. Any help or advice would be greatly appreciated.
