### ISSUE TITLE
New to This

### ISSUE THREAD

**Issue by bubblebobbledragon** [dylmeadows/EonTimer#76]
<img width="566" alt="Screen Shot 2020-05-21 at 1 59 04 PM" src="https://user-images.githubusercontent.com/65733136/82595501-4a628d00-9b6b-11ea-8913-38aafa4d3784.png">

Downloaded all the needed components including the right java version, and it still gives me this error. I know I'm clicking the right script & checked the other questions before posting so I am unsure what I'm doing wrong..I'm also using a Mac.
Thanks for reading.

**Comment by dylmeadows** [comment]
What I use to run it on macOS is [sdkman](https://sdkman.io). After installing sdkman, run `sdk install java 8.0.232.fx-zulu`. This is a specific version of Java that contains the UI framework. It should work then. Let me know if it doesn't.
