### ISSUE TITLE
Assistance building EonTimer on Debian Bullseye

### ISSUE THREAD

**Issue by tha-chunginator** [dylmeadows/EonTimer#79]
Hi, I am have a lot of experience compiling with Qt but since the platform needed to build EonTimer is cmake, my experince is very limited. On the compiling from source wiki, I didn't get much direction. I at least know that my cmake version is able to compile it (3.16.3). I messed around for a little while but didn't really get anywhere. Thanks in advance for the help!

**Comment by tha-chunginator** [comment]
When I try to compile it, it says:
CMake Error at CMakeLists.txt:31 (find_package):
  By not providing "FindSFML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SFML", but
  CMake did not find one.

  Could not find a package configuration file provided by "SFML" (requested
  version 2.4) with any of the following names:

    SFMLConfig.cmake
    sfml-config.cmake

  Add the installation prefix of "SFML" to CMAKE_PREFIX_PATH or set
  "SFML_DIR" to a directory containing one of the above files.  If "SFML"
  provides a separate development package or SDK, be sure it has been
  installed.
what can I do to fix this?

**Comment by tha-chunginator** [comment]
If you could also build an earlier version on qmake that would also be okay. For some reason I couldn't clone into the git repository to get the source code.

**Comment by tha-chunginator** [comment]
Ok so I solved the SFML issue, but now when I run make this issue occurs:
[  2%] Automatic MOC for target EonTimer
[  2%] Built target EonTimer_autogen
make[2]: *** No rule to make target 'resources/styles/main.css', needed by 'EonTimer_autogen/3YJK5W5UP7/qrc_resources.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/EonTimer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by dylmeadows** [comment]
Sorry for taking so long to respond. The styles have to be transpiled with [qtsass ](https://github.com/spyder-ide/qtsass)

**Comment by tha-chunginator** [comment]
What steps do I need to take to do that? I’ve never heard of qtsass

**Comment by dylmeadows** [comment]
Install qtsass with pip (https://pypi.org/project/qtsass/). After that's installed run `./ci/linux/before_build.sh` that will use qtsass to transpile the scss files into css. Build with cmake after that and it should go through fine.

**Comment by tha-chunginator** [comment]
Which directory do I run that in? I tried the EonTimer directory and the home directory but it can't find /ci/linux/before_build.sh.

**Comment by dylmeadows** [comment]
I realized there was a typo in my last comment. It should be `./.ci/linux/before_build.sh` and that should be run in the EonTimer directory.

**Comment by tha-chunginator** [comment]
Thanks for your help! Got it working!
