### ISSUE TITLE
Eon timer Java errors 

### ISSUE THREAD

**Issue by Titanz76** [dylmeadows/EonTimer#80]
Hey I’ve been trying to use eon timer for 2.1 and every time I try to open the batch file a black screen pops up and immediately closes. I’ve already download the Java jre file for windows 64 and I still keep getting this issue can someone please help I’m so desperate at this point.

**Comment by Titanz76** [comment]
I’m really desperate can someone help please!

**Comment by Titanz76** [comment]
Dylmeadows please help!!

**Comment by tha-chunginator** [comment]
If you are trying to RNG for gens 4 or 5, here is an online alternative to EonTimer (btw I couldn't get it to work either). 
https://not-an-aardvark.github.io/rng-timer/

**Comment by dylmeadows** [comment]
@Titanz76 sorry for taking so long to respond. If you are on Windows, try using https://ci.appveyor.com/project/dylmeadows/eontimer/builds/33044891/job/c6qd4orbex50xc6o/artifacts instead. It's a development build of the 3.0.0 release. Doesn't require java and should be more accurate

**Comment by Titanz76** [comment]
Thank you very much man much luv!
