### ISSUE TITLE
Timer frozen every few runs

### ISSUE THREAD

**Issue by idkmanwtt** [dylmeadows/EonTimer#81]
I'm really about to delete everything and find another timer, it's so frustrating. Whenever it's time for the beeps, the timer freezes on a random time, with the blue background, say 2:20. This causes EonTimer to freeze completely, thus having to be restarted. Even after restarting, it sometimes happens right away again, thee's no pattern. It's ruined SO many of my rng attempts I can't even count them anymore.

Edit: using Windows 10

**Comment by dylmeadows** [comment]
What version are you using?

**Comment by idkmanwtt** [comment]
2.0.1

**Comment by dylmeadows** [comment]
There is a newer version that hasn't been released yet that should be easier to run (doesn't require Java) and should be more accurate and stable. 2.x isn't going to be maintained anymore going forward.

You can download it here: 
- Windows (64-Bit): https://ci.appveyor.com/project/dylmeadows/eontimer/builds/33044891/job/c6qd4orbex50xc6o/artifacts
- Windows (32-Bit): https://ci.appveyor.com/project/dylmeadows/eontimer/builds/33044891/job/sm32mahedg86k6sw/artifacts
- macOS: https://ci.appveyor.com/project/dylmeadows/eontimer/builds/33044891/job/xcgdu77ixnnio7dh/artifacts
- Ubuntu 18.04: https://ci.appveyor.com/project/dylmeadows/eontimer/builds/33044891/job/npoaa95ncrha2t7i/artifacts
