### ISSUE TITLE
Unable to run it on Windows

### ISSUE THREAD

**Issue by Conando025** [dylmeadows/EonTimer#84]
I'm using JDK 15.0.1 and EonTimer 2.0.1 but when I try and run the batch file from the command line I get the following error:
```
Error: Could not find or load main class io.github.dylmeadows.eontimer.AppLauncher 
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

Any ideas on how to fix this?

**Comment by dylmeadows** [comment]
EonTimer 2.0.1 requires JDK 8 with JavaFX included (can be found in Oracle's JDK 8)

**Comment by dylmeadows** [comment]
As an alternative, try using the artifacts found [here](https://ci.appveyor.com/project/dylmeadows/eontimer/build/job/c6qd4orbex50xc6o/artifacts) instead. Should work natively on windows without a JVM
